### ISSUE TITLE
Rout.js error 

### ISSUE THREAD

**Issue by asirihewage** [asirihewage/Procurement-for-Construction-Industry#17]
This thing happens each time I merge your commits. Please review. 

./src/Routes.js
Module not found: Can't resolve './components/banuka/Banuka' in 'E:\SLIIT\Projects\CSSE-ProjectProcureSystem-2019\Client\src'

**Comment by iamdempa** [comment]
I made a new PR with the fix. I guess it should be working now. If not, please let me know.

note: did you pull the updated repo before running the app?
