### ISSUE TITLE
Restrict the write access

### ISSUE THREAD

**Issue by iamdempa** [asirihewage/Procurement-for-Construction-Industry#6]
Please restrict the write access to the **origin** repository (this one) directly. Anyone trying to **commit** or **merge** their branches **SHOULD NOT BE** directly merged to the branch. Every merge **SHOULD BE SUPERVISED BY THE REPO OWNER (i.e. Asiri Hewage)** then only the changes will be merged and reflected.

**Comment by asirihewage** [comment]
resolved
